index:
    path: /
    controller: App\Controller\DefaultController::index
post_list:
    path: /post
    controller: App\Controller\PostController::list
post_single:
    path: /post/{slug}
    controller: App\Controller\PostController::single